# -*- coding: utf-8 -*-
"""colab-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFN4E26gfA1IXtROjgX_WsbuhuTFkHm1

# 流程

讀取 train_df / test_df

      ↓

檢查資料結構

      ↓

切出 X / y

      ↓

移除不適合直接建模的欄位

      ↓

Train / Validation Split

      ↓

LightGBM Baseline

      ↓

模型評估（Precision / Recall / F1）

      ↓

Feature Importance

      ↓

Threshold Tuning

      ↓
      
產出 test prediction / submission

# Colab-2：BitoGuard 建模與評估

這份 notebook 的任務是使用 Colab-1 輸出的 train_df 與 test_df 進行模型訓練與評估。
我們會先建立 baseline model，再透過 feature importance 與 threshold tuning 優化 fraud detection 效果。


### 本 notebook 的輸入與輸出


輸入：

	•	train_df.csv
	•	test_df.csv

輸出：

	•	baseline 模型評估結果
	•	feature importance
	•	最佳 threshold
	•	submission.csv
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_curve,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score
)

import lightgbm as lgb
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

try:
    import optuna
    optuna.logging.set_verbosity(optuna.logging.WARNING)
    HAS_OPTUNA = True
except ImportError:
    HAS_OPTUNA = False
    print("optuna 未安裝，跳過自動調參。可執行: pip install optuna xgboost")

"""## 載入套件

這一步會載入建模所需的套件：

	•	pandas, numpy：資料處理
	•	train_test_split：切分 train / validation
	•	classification_report, confusion_matrix：評估模型
	•	precision_recall_curve, f1_score：做 threshold tuning
	•	lightgbm：baseline 模型
	•	matplotlib：畫圖

## 讀取 Colab-1 輸出的資料

這裡直接讀取 Colab-1 產生的 train_df 與 test_df。
這樣就不需要重新跑 API、EDA 與特徵工程，可以把資料工程與模型工程分開。
"""

train_df = pd.read_csv("train_df.csv")
test_df = pd.read_csv("test_df.csv")

print("train_df:", train_df.shape)
print("test_df:", test_df.shape)

"""### 驗證資料是否讀取正確

正常情況下：

	•	train_df 應該比 test_df 多一欄 status
	•	筆數應該約為 51,017 與 12,753
	•	user_id 應該存在於兩張表
"""

print(train_df.columns.tolist()[:20])
print(test_df.columns.tolist()[:20])

print("status in train_df:", "status" in train_df.columns)
print("status in test_df:", "status" in test_df.columns)

# 再次確認 label distribution
print(train_df["status"].value_counts())
print(train_df["status"].value_counts(normalize=True))

"""## 建立特徵矩陣 X 與標籤 y

這一步會把訓練資料拆成：

	•	X：模型輸入特徵
	•	y：要預測的目標欄位 status

同時測試資料也會切出 test_X。
"""

y = train_df["status"]
X = train_df.drop(columns=["status"]).copy()
test_X = test_df.copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("test_X shape:", test_X.shape)

"""## 移除不適合直接建模的欄位

文字內容

有些欄位不能直接丟進模型，例如：

	•	user_id：只是識別碼，不是行為特徵
	•	datetime 欄位：LightGBM 不能直接吃 datetime 型別

所以我們要先把這些欄位移除，建立純數值的 baseline 版本
"""

# 找出 datetime 欄位
datetime_cols = X.select_dtypes(include=["datetime64[ns]", "datetime64[ns, UTC]"]).columns.tolist()
print("datetime_cols:", datetime_cols)

# 額外移除已知的時間欄位（可能是 object 類型）
time_related_cols = [
    "confirmed_at", "level1_finished_at", "level2_finished_at",
    "twd_first_time", "twd_last_time", 
    "crypto_first_time", "crypto_last_time",
    "trade_first_time", "trade_last_time",
    "swap_first_time", "swap_last_time",
    "overall_first_time", "overall_last_time"
]

# 移除 datetime 欄位和時間相關欄位
all_drop_cols = datetime_cols + time_related_cols + ["user_id"]
X = X.drop(columns=all_drop_cols, errors="ignore")
test_X = test_X.drop(columns=all_drop_cols, errors="ignore")

print("X shape after drop:", X.shape)
print("test_X shape after drop:", test_X.shape)

# 檢查並移除任何剩餘的非數值欄位
non_numeric_cols = X.select_dtypes(exclude=["int", "float", "bool"]).columns.tolist()
if len(non_numeric_cols) > 0:
    print(f"\n⚠️ 發現非數值欄位: {non_numeric_cols}")
    print("正在移除...")
    X = X.drop(columns=non_numeric_cols)
    test_X = test_X.drop(columns=non_numeric_cols, errors="ignore")
    print(f"移除後 X shape: {X.shape}")
else:
    print("\n✅ 所有欄位都是數值型")

"""## 處理 object 類型欄位

如果還有 object 欄位，baseline 階段先做簡單編碼。
不過因為 Colab-1 的特徵大多已經是數值，理論上剩下的 object 欄位應該不多。
"""

print(X.dtypes.value_counts())

"""## Train / Validation Split

因為本題是高度不平衡分類，所以切分資料時一定要使用：

stratify=y

這樣可以確保 train 與 validation 中的 suspicious user 比例相近，避免評估失真
"""

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)
print("y_train positive rate:", y_train.mean())
print("y_valid positive rate:", y_valid.mean())

"""建立 LightGBM baseline model

這裡使用 LightGBM 作為 baseline model，原因是：

	•	很適合 tabular data
	•	不需要特徵標準化
	•	訓練速度快
	•	對非線性特徵關係有不錯表現

此外，因為本題是 class imbalance，我們會先使用：

class_weight="balanced"

讓模型自動提高少數類別的重要性。
"""

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"pos_weight: {pos_weight:.2f}")

# ============================================================
# 策略 1: Optuna 自動調參 LightGBM
# ============================================================

def find_best_threshold(y_true, y_prob):
    """在 validation set 上找最佳 F1 threshold"""
    thresholds = np.arange(0.01, 0.6, 0.005)
    best_f1, best_th = 0, 0.5
    for th in thresholds:
        f1 = f1_score(y_true, (y_prob >= th).astype(int), zero_division=0)
        if f1 > best_f1:
            best_f1, best_th = f1, th
    return best_th, best_f1


if HAS_OPTUNA:
    print("\n[Optuna] 自動調參中（50 trials）...")

    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 200, 800),
            "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.05, log=True),
            "num_leaves": trial.suggest_int("num_leaves", 31, 255),
            "max_depth": trial.suggest_int("max_depth", 4, 10),
            "min_child_samples": trial.suggest_int("min_child_samples", 20, 200),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-4, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-4, 10.0, log=True),
            "scale_pos_weight": pos_weight,
            "random_state": 42,
            "verbose": -1,
        }
        m = lgb.LGBMClassifier(**params)
        m.fit(
            X_train, y_train,
            eval_set=[(X_valid, y_valid)],
            eval_metric="auc",
            callbacks=[lgb.early_stopping(50, verbose=False), lgb.log_evaluation(-1)]
        )
        prob = m.predict_proba(X_valid)[:, 1]
        _, best_f1 = find_best_threshold(y_valid, prob)
        return best_f1

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=50, show_progress_bar=False)

    best_params = study.best_params
    best_params["scale_pos_weight"] = pos_weight
    best_params["random_state"] = 42
    best_params["verbose"] = -1
    print(f"[Optuna] 最佳 F1: {study.best_value:.4f}")
    print(f"[Optuna] 最佳參數: {best_params}")
else:
    # 手動調好的參數（不需要 Optuna）
    best_params = {
        "n_estimators": 500,
        "learning_rate": 0.02,
        "num_leaves": 127,
        "max_depth": 7,
        "min_child_samples": 50,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "reg_alpha": 0.1,
        "reg_lambda": 1.0,
        "scale_pos_weight": pos_weight,
        "random_state": 42,
        "verbose": -1,
    }
    print("[手動參數] 使用預設調好的參數")

# ============================================================
# 策略 2: Stratified K-Fold OOF 訓練（5 fold）
# 同時訓練 LightGBM + XGBoost，最後 ensemble
# ============================================================

print("\n[K-Fold] 開始 5-Fold OOF 訓練...")

N_FOLDS = 5
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)

X_arr = X.values
y_arr = y.values
test_arr = test_X.values

# OOF 預測容器
oof_lgb  = np.zeros(len(X_arr))
oof_xgb  = np.zeros(len(X_arr))
test_lgb = np.zeros(len(test_arr))
test_xgb = np.zeros(len(test_arr))

for fold, (tr_idx, val_idx) in enumerate(skf.split(X_arr, y_arr)):
    print(f"  Fold {fold+1}/{N_FOLDS}...", end=" ")

    Xtr, Xval = X_arr[tr_idx], X_arr[val_idx]
    ytr, yval = y_arr[tr_idx], y_arr[val_idx]

    # --- LightGBM ---
    lgb_model = lgb.LGBMClassifier(**best_params)
    lgb_model.fit(
        Xtr, ytr,
        eval_set=[(Xval, yval)],
        eval_metric="auc",
        callbacks=[lgb.early_stopping(100, verbose=False), lgb.log_evaluation(-1)]
    )
    oof_lgb[val_idx]  = lgb_model.predict_proba(Xval)[:, 1]
    test_lgb          += lgb_model.predict_proba(test_arr)[:, 1] / N_FOLDS

    # --- XGBoost ---
    xgb_pw = (ytr == 0).sum() / (ytr == 1).sum()
    xgb_model = xgb.XGBClassifier(
        n_estimators=500,
        learning_rate=0.02,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=xgb_pw,
        eval_metric="auc",
        early_stopping_rounds=100,
        random_state=42,
        verbosity=0,
    )
    xgb_model.fit(
        Xtr, ytr,
        eval_set=[(Xval, yval)],
        verbose=False
    )
    oof_xgb[val_idx]  = xgb_model.predict_proba(Xval)[:, 1]
    test_xgb          += xgb_model.predict_proba(test_arr)[:, 1] / N_FOLDS

    f1_fold = f1_score(yval, (oof_lgb[val_idx] >= 0.5).astype(int), zero_division=0)
    print(f"LGB OOF AUC={roc_auc_score(yval, oof_lgb[val_idx]):.4f}")

# ============================================================
# 策略 3: Ensemble（加權平均）+ 最佳 threshold
# ============================================================

print("\n[Ensemble] 搜尋最佳 ensemble 權重...")

best_ensemble_f1 = 0
best_w = 0.5

for w in np.arange(0.3, 0.8, 0.05):
    oof_blend = w * oof_lgb + (1 - w) * oof_xgb
    _, f1_blend = find_best_threshold(y_arr, oof_blend)
    if f1_blend > best_ensemble_f1:
        best_ensemble_f1 = f1_blend
        best_w = w

print(f"最佳 LGB 權重: {best_w:.2f}, XGB 權重: {1-best_w:.2f}")
print(f"Ensemble OOF F1: {best_ensemble_f1:.4f}")

# 最終 OOF 機率
valid_prob = best_w * oof_lgb + (1 - best_w) * oof_xgb

# 找最佳 threshold（在完整 OOF 上）
best_th, best_f1_oof = find_best_threshold(y_arr, valid_prob)
print(f"最佳 threshold: {best_th:.3f}  OOF F1: {best_f1_oof:.4f}")

# 直接用完整 OOF 評估
best_pred = (valid_prob >= best_th).astype(int)

# 保留 model 變數供後面 feature importance 使用
model = lgb_model  # 最後一個 fold 的 lgb model

"""## Baseline 預測與評估

這一步先用模型預設 threshold = 0.5 進行預測，並檢查：

	•	confusion matrix
	•	precision
	•	recall
	•	F1-score

特別要關注的是 status=1 的表現，因為那才是 suspicious users。
"""

# OOF 整體評估
print("=== OOF 整體評估（Ensemble）===")
print("Confusion Matrix:")
print(confusion_matrix(y_arr, best_pred))
print("\nClassification Report:")
print(classification_report(y_arr, best_pred))
print(f"OOF AUC: {roc_auc_score(y_arr, valid_prob):.4f}")

"""## 如何解讀 baseline 評估結果

這一步不要只看 accuracy。
對本題來說，更重要的是：

	•	Precision：被模型標成 suspicious 的帳戶，有多少是真的
	•	Recall：所有真的 suspicious 帳戶裡，模型抓到了多少
	•	F1-score：Precision 與 Recall 的平衡

因為這是 fraud detection 問題，如果完全抓不到 suspicious users，就算 accuracy 很高也沒有意義。

"""

importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
}).sort_values("importance", ascending=False)

importance.head(20)

plt.figure(figsize=(10, 8))
top_k = 20
plt.barh(
    importance["feature"].head(top_k)[::-1],
    importance["importance"].head(top_k)[::-1]
)
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 20 Feature Importance")
plt.tight_layout()
plt.show()

"""## Feature Importance

如果重要特徵集中在：

	•	出入金比例
	•	crypto 交易總額
	•	unique wallet / unique IP
	•	夜間交易比例
	•	API / market order 行為

那其實代表模型學到的是合理的 AML 行為模式，而不是單純記住 ID。


### Threshold Tuning

在不平衡分類問題中，預設 threshold = 0.5 往往不是最好的選擇。
因此我們要透過 validation set 找出能讓 F1-score 最佳的 threshold。

"""

# threshold tuning 已在 K-Fold 階段完成，這裡用 OOF 機率重新掃一次做視覺化
records = []
for th in np.arange(0.01, 0.6, 0.005):
    pred_th = (valid_prob >= th).astype(int)
    p = precision_score(y_arr, pred_th, zero_division=0)
    r = recall_score(y_arr, pred_th, zero_division=0)
    f1 = f1_score(y_arr, pred_th, zero_division=0)
    records.append((th, p, r, f1))

threshold_df = pd.DataFrame(records, columns=["threshold", "precision", "recall", "f1"])
print("Top 10 threshold:")
print(threshold_df.sort_values("f1", ascending=False).head(10))

"""### 找出最佳 threshold

這一步會找到在 validation set 上 F1-score 最好的 threshold，並用它取代預設的 0.5。
這在 fraud detection 裡非常常見，因為不同業務場景對 false positive 與 false negative 的容忍度不同。
"""

best_row = threshold_df.sort_values("f1", ascending=False).iloc[0]
best_th = float(best_row["threshold"])

print(f"最佳 threshold: {best_th:.3f}")
print(best_row)

best_pred = (valid_prob >= best_th).astype(int)

print("\nConfusion Matrix (OOF, best threshold):")
print(confusion_matrix(y_arr, best_pred))

print("\nClassification Report (OOF, best threshold):")
print(classification_report(y_arr, best_pred))

"""### Threshold Tuning 的解讀

這一步通常會看到：

	•	threshold 降低時 recall 變高
	•	但 precision 可能下降
	•	F1 會在某個 threshold 達到平衡最佳值

這可以幫助我們根據業務需求選擇更合適的 decision rule。
"""

plt.figure(figsize=(8, 5))
plt.plot(threshold_df["threshold"], threshold_df["precision"], label="Precision")
plt.plot(threshold_df["threshold"], threshold_df["recall"], label="Recall")
plt.plot(threshold_df["threshold"], threshold_df["f1"], label="F1")
plt.axvline(x=best_th, color="red", linestyle="--", label=f"Best th={best_th:.3f}")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title("Precision / Recall / F1 vs Threshold (OOF Ensemble)")
plt.legend()
plt.tight_layout()
plt.show()

# 用 ensemble 機率預測 test set
test_prob = best_w * test_lgb + (1 - best_w) * test_xgb
test_pred = (test_prob >= best_th).astype(int)

print(f"\nTest 預測詐騙數: {test_pred.sum()} / {len(test_pred)} ({test_pred.mean():.2%})")

submission = pd.DataFrame({
    "user_id": test_df["user_id"],
    "status": test_pred
})

submission.head()

"""# 儲存 submission"""

submission.to_csv("submission.csv", index=False)
print("submission.csv saved")

"""# Colab-2 總結

這份 notebook 完成了：

	•	讀取 Colab-1 輸出的 user-level 資料
	•	建立 baseline model
	•	評估 fraud detection 表現
	•	分析 feature importance
	•	進行 threshold tuning
	•	產出最終 submission

這樣整個專案就形成了完整的兩階段 pipeline：

	•	Colab-1：資料工程
	•	Colab-2：模型工程

"""