# -*- coding: utf-8 -*-
"""Colab-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKy_0ACcm_GuLlDh9h0K1hJr_YQ2wXR7

# 流程
API / PostgREST

      ↓

Pagination Fetch

      ↓

DataFrame

      ↓

CSV / Drive Storage

      ↓
EDA

      ↓
Data Cleaning

      ↓
Feature Engineering

      ↓
User-level Dataset

      ↓
輸出 train_df / test_df 給 Colab-2 建模

這份 notebook 最終會輸出三個重要結果：

feature_df：每個 user 一列的特徵總表

train_df：含 status 標籤的訓練資料

test_df：待預測的測試資料

這樣我們就能把資料工程和模型工程拆開，讓後續實驗更快、更乾淨

### 載入套件

講解稿

這一步是載入後面會用到的 Python 套件：

requests：呼叫 API

pandas：表格處理

numpy：數值運算

time：分頁抓資料時稍微停頓，避免對 API 打太快
"""

import requests
import pandas as pd
import numpy as np
import time
from IPython.display import display

"""### 先測試 API 是否能連線

網址是否正確

API 是否可用

回傳格式是不是 JSON list

# 資料抓取與特徵工程
"""

url = "https://aws-event-api.bitopro.com/train_label"
r = requests.get(url)

print("status code:", r.status_code)
print("first 3 rows:")
print(r.json()[:3])

"""### 建立可重複使用的 API 抓表函式

因為我們不只要抓一張表，而是要抓 user_info、twd_transfer、crypto_transfer、usdt_twd_trading、usdt_swap、train_label、predict_label 這幾張表，所以不能每張都手寫一次。

這裡我們先寫一個最基礎的函式：給表名，就把 API 回傳資料變成 DataFrame。
"""

def fetch_table_simple(name, limit=100000):
    url = f"https://aws-event-api.bitopro.com/{name}?limit={limit}"
    r = requests.get(url)
    r.raise_for_status()
    data = r.json()
    df = pd.DataFrame(data)
    print(name, df.shape)
    return df

# 我們先抓 user_info 看看格式。這一步的目的是確認：表名對不對、欄位是不是和文件一致、單次抓取能不能成功
user_info_demo = fetch_table_simple("user_info")
user_info_demo.head()

"""為什麼不能只用 fetch_table_simple

因為大表資料量超過單次抓取上限。例如：

twd_transfer 約 195k 筆

crypto_transfer 約 239k 筆

usdt_twd_trading 約 217k 筆

如果只抓一次，就會被截斷。所以我們需要 Pagination（分頁抓取）

分頁抓取的核心是兩個參數：

limit：一次抓幾筆

offset：從第幾筆開始抓

我們會用 while loop 反覆抓下一批，直到沒有資料為止。
"""

def fetch_table_paginated(name, batch_size=50000):
    all_dfs = []
    offset = 0

    while True:
        url = f"https://aws-event-api.bitopro.com/{name}?limit={batch_size}&offset={offset}"
        r = requests.get(url)
        r.raise_for_status()
        data = r.json()

        if len(data) == 0:
            print(f"{name}: no more rows, stop at offset={offset}")
            break

        df_batch = pd.DataFrame(data)
        all_dfs.append(df_batch)

        print(f"{name}: fetched {len(df_batch)} rows, offset={offset}")
        offset += batch_size
        time.sleep(0.2)

    final_df = pd.concat(all_dfs, ignore_index=True)
    print(f"{name}: final shape = {final_df.shape}")
    return final_df

"""all_dfs = []：存每一批抓回來的 DataFrame

offset = 0：從第一筆開始抓

while True：持續抓下一批

if len(data) == 0：若 API 回空資料，表示抓完了

pd.concat(all_dfs)：把所有批次合併成一張完整表

## 抓所有資料表
接下來會抓 7 張表：

user_info

twd_transfer

crypto_transfer

usdt_twd_trading

usdt_swap

train_label

predict_label

這一步可能要一點時間，因為大表需要分批抓。
"""

user_info = fetch_table_paginated("user_info", batch_size=50000)
twd_transfer = fetch_table_paginated("twd_transfer", batch_size=50000)
crypto_transfer = fetch_table_paginated("crypto_transfer", batch_size=50000)
usdt_twd_trading = fetch_table_paginated("usdt_twd_trading", batch_size=50000)
usdt_swap = fetch_table_paginated("usdt_swap", batch_size=50000)
train_label = fetch_table_paginated("train_label", batch_size=50000)
predict_label = fetch_table_paginated("predict_label", batch_size=50000)

"""### 驗證抓回來的資料量

這一步要確認實際抓回來的筆數是否和題目提供的資料量相近。如果數量差太多，通常表示：

分頁沒有抓完整

API 被截斷

表名拼錯
"""

print("user_info:", user_info.shape)
print("twd_transfer:", twd_transfer.shape)
print("crypto_transfer:", crypto_transfer.shape)
print("usdt_twd_trading:", usdt_twd_trading.shape)
print("usdt_swap:", usdt_swap.shape)
print("train_label:", train_label.shape)
print("predict_label:", predict_label.shape)

"""### 存成本地檔案"""

user_info.to_csv("user_info.csv", index=False)
twd_transfer.to_csv("twd_transfer.csv", index=False)
crypto_transfer.to_csv("crypto_transfer.csv", index=False)
usdt_twd_trading.to_csv("usdt_twd_trading.csv", index=False)
usdt_swap.to_csv("usdt_swap.csv", index=False)
train_label.to_csv("train_label.csv", index=False)
predict_label.to_csv("predict_label.csv", index=False)

"""## 初步 EDA：看每張表的結構

在進行清洗前，我們要先做資料檢查。這一步的目的是看：

欄位長什麼樣

型別是不是合理

哪些欄位有缺值

時間欄位是不是還是字串
"""

dfs = {
    "user_info": user_info,
    "twd_transfer": twd_transfer,
    "crypto_transfer": crypto_transfer,
    "usdt_twd_trading": usdt_twd_trading,
    "usdt_swap": usdt_swap,
    "train_label": train_label,
    "predict_label": predict_label
}

for name, df in dfs.items():
    print("=" * 100)
    print(name)
    print("shape:", df.shape)
    print("\ncolumns:")
    print(df.columns.tolist())
    print("\ndtypes:")
    print(df.dtypes)
    print("\nmissing values:")
    print(df.isnull().sum().sort_values(ascending=False).head(10))
    display(df.head())

"""### EDA 的重點觀察

這一步通常會看到幾個重要現象：

時間欄位多半還是 object，需要轉成 datetime

金額欄位多半是放大後整數，後面要乘 1e-8

crypto_transfer 的部分缺值不是髒資料，而是業務訊號

所有表都能靠 user_id 串起來，代表很適合做 user-level aggregation

## 檢查 label 分布

這一步是本題最重要的 EDA 之一。因為命題文件已經提醒這是 非平衡資料，所以我們要確認 status=1 到底少到什麼程度。
"""

print(train_label["status"].value_counts())
print(train_label["status"].value_counts(normalize=True))

"""## label 分布的解讀

如果你看到 status=1 只有大約 3% 左右，代表這是一個典型的 fraud detection / AML 不平衡分類問題。這意味著：

不能只看 accuracy

train/valid split 要用 stratify=y

模型要處理 class imbalance

後面要特別關注 precision / recall / F1-score

# Data Cleaning：把資料變成可計算、可聚合、可建模

接下來進入資料清洗。清洗階段的主要工作有三類：

時間欄位轉型

金額欄位還原真實值

新增一些中間旗標欄位，方便後面做 aggregation

### user_info 清洗說明

user_info 是 user-level 主表。這裡我們做了兩類轉換：

把 KYC 相關時間欄位轉成 datetime

產生 KYC 完成旗標與時間差特徵

這些特徵後面可以反映：

是否完成 KYC

完成 KYC 的速度

KYC 流程是否異常快
"""

user_info = user_info.copy()

for col in ["confirmed_at", "level1_finished_at", "level2_finished_at"]:
    user_info[col] = pd.to_datetime(user_info[col], errors="coerce")

user_info["has_confirmed"] = user_info["confirmed_at"].notna().astype(int)
user_info["has_level1"] = user_info["level1_finished_at"].notna().astype(int)
user_info["has_level2"] = user_info["level2_finished_at"].notna().astype(int)

user_info["lvl1_minus_confirm_sec"] = (
    user_info["level1_finished_at"] - user_info["confirmed_at"]
).dt.total_seconds()

user_info["lvl2_minus_lvl1_sec"] = (
    user_info["level2_finished_at"] - user_info["level1_finished_at"]
).dt.total_seconds()

user_info.head()

"""### twd_transfer 清洗說明

這張表是法幣出入金紀錄。做了：

created_at 轉 datetime

ori_samount 還原成真實金額

kind 拆成 is_deposit / is_withdraw

新增 hour 與 is_night

這樣後面就能直接計算：

入金次數

出金次數

出入金比例

夜間法幣操作比例


"""

twd_transfer = twd_transfer.copy()

twd_transfer["created_at"] = pd.to_datetime(twd_transfer["created_at"], errors="coerce")
twd_transfer["amount"] = twd_transfer["ori_samount"] * 1e-8

twd_transfer["is_deposit"] = (twd_transfer["kind"] == 0).astype(int)
twd_transfer["is_withdraw"] = (twd_transfer["kind"] == 1).astype(int)

twd_transfer["hour"] = twd_transfer["created_at"].dt.hour
twd_transfer["is_night"] = twd_transfer["hour"].between(0, 5).astype(int)

twd_transfer.head()

"""### crypto_transfer 清洗說明

這張表最複雜，也是最有價值的一張。我們做了：

還原 crypto 金額與台幣匯率

估算每筆交易的台幣價值 twd_value

拆出 deposit / withdraw

拆出 external / internal

將缺值資訊轉成旗標，例如 has_relation_user

新增夜間交易欄位

注意：像 relation_user_id、source_ip_hash 的缺值，很多時候不是資料壞掉，而是有業務意義。
"""

crypto_transfer = crypto_transfer.copy()

crypto_transfer["created_at"] = pd.to_datetime(crypto_transfer["created_at"], errors="coerce")
crypto_transfer["crypto_amount"] = crypto_transfer["ori_samount"] * 1e-8
crypto_transfer["twd_rate"] = crypto_transfer["twd_srate"] * 1e-8
crypto_transfer["twd_value"] = crypto_transfer["crypto_amount"] * crypto_transfer["twd_rate"]

crypto_transfer["is_deposit"] = (crypto_transfer["kind"] == 0).astype(int)
crypto_transfer["is_withdraw"] = (crypto_transfer["kind"] == 1).astype(int)
crypto_transfer["is_external"] = (crypto_transfer["sub_kind"] == 0).astype(int)
crypto_transfer["is_internal"] = (crypto_transfer["sub_kind"] == 1).astype(int)

crypto_transfer["has_relation_user"] = crypto_transfer["relation_user_id"].notna().astype(int)
crypto_transfer["has_source_ip"] = crypto_transfer["source_ip_hash"].notna().astype(int)
crypto_transfer["has_from_wallet"] = crypto_transfer["from_wallet_hash"].notna().astype(int)
crypto_transfer["has_to_wallet"] = crypto_transfer["to_wallet_hash"].notna().astype(int)

crypto_transfer["hour"] = crypto_transfer["created_at"].dt.hour
crypto_transfer["is_night"] = crypto_transfer["hour"].between(0, 5).astype(int)

crypto_transfer.head()

"""### usdt_twd_trading 清洗說明

這張表是掛單簿成交資料，能反映交易風格。我們把：

成交數量

成交價格

買單 / 賣單

夜間交易

都整理成後面可聚合的欄位。


"""

usdt_twd_trading = usdt_twd_trading.copy()

usdt_twd_trading["updated_at"] = pd.to_datetime(usdt_twd_trading["updated_at"], errors="coerce")
usdt_twd_trading["amount"] = usdt_twd_trading["trade_samount"] * 1e-8
usdt_twd_trading["price"] = usdt_twd_trading["twd_srate"] * 1e-8

usdt_twd_trading["is_sell"] = (usdt_twd_trading["is_buy"] == 0).astype(int)

usdt_twd_trading["hour"] = usdt_twd_trading["updated_at"].dt.hour
usdt_twd_trading["is_night"] = usdt_twd_trading["hour"].between(0, 5).astype(int)

usdt_twd_trading.head()

"""### usdt_swap 清洗說明

這張表是簡化的一鍵買賣紀錄，通常比較反映零售型操作。我們將它轉成：

買幣 / 賣幣旗標

真實金額

夜間操作欄位

方便後續彙總成 user-level 特徵。
"""

usdt_swap = usdt_swap.copy()

usdt_swap["created_at"] = pd.to_datetime(usdt_swap["created_at"], errors="coerce")
usdt_swap["twd_amount"] = usdt_swap["twd_samount"] * 1e-8
usdt_swap["crypto_amount"] = usdt_swap["currency_samount"] * 1e-8

usdt_swap["is_buy_coin"] = (usdt_swap["kind"] == 0).astype(int)
usdt_swap["is_sell_coin"] = (usdt_swap["kind"] == 1).astype(int)

usdt_swap["hour"] = usdt_swap["created_at"].dt.hour
usdt_swap["is_night"] = usdt_swap["hour"].between(0, 5).astype(int)

usdt_swap.head()

# =========================
# v2: add advanced time / log features
# =========================

# twd_transfer
twd_transfer["amount_log"] = np.log1p(twd_transfer["amount"])
twd_transfer["day_of_week"] = twd_transfer["created_at"].dt.dayofweek
twd_transfer["date_only"] = twd_transfer["created_at"].dt.date
twd_transfer["is_weekend"] = (twd_transfer["day_of_week"] >= 5).astype(int)

# crypto_transfer
crypto_transfer["crypto_amount_log"] = np.log1p(crypto_transfer["crypto_amount"])
crypto_transfer["twd_value_log"] = np.log1p(crypto_transfer["twd_value"])
crypto_transfer["day_of_week"] = crypto_transfer["created_at"].dt.dayofweek
crypto_transfer["date_only"] = crypto_transfer["created_at"].dt.date
crypto_transfer["is_weekend"] = (crypto_transfer["day_of_week"] >= 5).astype(int)

# usdt_twd_trading
usdt_twd_trading["amount_log"] = np.log1p(usdt_twd_trading["amount"])
usdt_twd_trading["price_log"] = np.log1p(usdt_twd_trading["price"])
usdt_twd_trading["day_of_week"] = usdt_twd_trading["updated_at"].dt.dayofweek
usdt_twd_trading["date_only"] = usdt_twd_trading["updated_at"].dt.date
usdt_twd_trading["is_weekend"] = (usdt_twd_trading["day_of_week"] >= 5).astype(int)

# usdt_swap
usdt_swap["twd_amount_log"] = np.log1p(usdt_swap["twd_amount"])
usdt_swap["crypto_amount_log"] = np.log1p(usdt_swap["crypto_amount"])
usdt_swap["day_of_week"] = usdt_swap["created_at"].dt.dayofweek
usdt_swap["date_only"] = usdt_swap["created_at"].dt.date
usdt_swap["is_weekend"] = (usdt_swap["day_of_week"] >= 5).astype(int)

def calc_time_gap_features(df, user_col, time_col, prefix):
    """
    對每個 user 計算相鄰交易間隔（秒）的統計特徵
    """
    tmp = df[[user_col, time_col]].dropna().sort_values([user_col, time_col]).copy()
    tmp["gap_sec"] = tmp.groupby(user_col)[time_col].diff().dt.total_seconds()

    gap_feat = tmp.groupby(user_col).agg(
        **{
            f"{prefix}_gap_mean_sec": ("gap_sec", "mean"),
            f"{prefix}_gap_std_sec": ("gap_sec", "std"),
            f"{prefix}_gap_min_sec": ("gap_sec", "min"),
            f"{prefix}_gap_max_sec": ("gap_sec", "max"),
        }
    ).reset_index()

    # burstiness = (std - mean) / (std + mean)
    gap_feat[f"{prefix}_burstiness"] = (
        (gap_feat[f"{prefix}_gap_std_sec"].fillna(0) - gap_feat[f"{prefix}_gap_mean_sec"].fillna(0)) /
        (gap_feat[f"{prefix}_gap_std_sec"].fillna(0) + gap_feat[f"{prefix}_gap_mean_sec"].fillna(0) + 1e-9)
    )

    return gap_feat


def calc_active_day_features(df, user_col, date_col, prefix):
    """
    每個 user 的活躍天數
    """
    feat = df.groupby(user_col).agg(
        **{
            f"{prefix}_active_days": (date_col, "nunique")
        }
    ).reset_index()
    return feat

"""# Feature Engineering：把 transaction-level 資料聚合成 user-level 特徵

現在所有中間欄位都準備好了。接下來要做的是把每張交易表按 user_id 聚合，變成每個 user 一列的行為摘要。

"""

# =========================
# twd_feat v2
# =========================

# overall
twd_feat = twd_transfer.groupby("user_id").agg(
    twd_txn_count=("id", "count"),
    twd_total_amount=("amount", "sum"),
    twd_avg_amount=("amount", "mean"),
    twd_max_amount=("amount", "max"),
    twd_min_amount=("amount", "min"),
    twd_std_amount=("amount", "std"),

    twd_avg_amount_log=("amount_log", "mean"),
    twd_max_amount_log=("amount_log", "max"),

    twd_deposit_count=("is_deposit", "sum"),
    twd_withdraw_count=("is_withdraw", "sum"),

    twd_night_ratio=("is_night", "mean"),
    twd_weekend_ratio=("is_weekend", "mean"),
    twd_unique_ip=("source_ip_hash", "nunique"),

    twd_first_time=("created_at", "min"),
    twd_last_time=("created_at", "max")
).reset_index()

# in / out 分開做
twd_in = twd_transfer[twd_transfer["is_deposit"] == 1].groupby("user_id").agg(
    twd_in_total_amount=("amount", "sum"),
    twd_in_avg_amount=("amount", "mean"),
    twd_in_max_amount=("amount", "max"),
    twd_in_std_amount=("amount", "std"),
    twd_in_avg_amount_log=("amount_log", "mean")
).reset_index()

twd_out = twd_transfer[twd_transfer["is_withdraw"] == 1].groupby("user_id").agg(
    twd_out_total_amount=("amount", "sum"),
    twd_out_avg_amount=("amount", "mean"),
    twd_out_max_amount=("amount", "max"),
    twd_out_std_amount=("amount", "std"),
    twd_out_avg_amount_log=("amount_log", "mean")
).reset_index()

# active days
twd_active_days = calc_active_day_features(
    twd_transfer, "user_id", "date_only", "twd"
)

# gap features
twd_gap_feat = calc_time_gap_features(
    twd_transfer, "user_id", "created_at", "twd"
)

# merge
twd_feat = twd_feat.merge(twd_in, on="user_id", how="left")
twd_feat = twd_feat.merge(twd_out, on="user_id", how="left")
twd_feat = twd_feat.merge(twd_active_days, on="user_id", how="left")
twd_feat = twd_feat.merge(twd_gap_feat, on="user_id", how="left")

# ratios
twd_feat["twd_withdraw_ratio"] = twd_feat["twd_withdraw_count"] / (twd_feat["twd_txn_count"] + 1e-9)
twd_feat["twd_deposit_ratio"] = twd_feat["twd_deposit_count"] / (twd_feat["twd_txn_count"] + 1e-9)
twd_feat["twd_withdraw_deposit_ratio"] = twd_feat["twd_withdraw_count"] / (twd_feat["twd_deposit_count"] + 1)
twd_feat["twd_txn_per_active_day"] = twd_feat["twd_txn_count"] / (twd_feat["twd_active_days"] + 1)

twd_feat["twd_out_in_amount_ratio"] = twd_feat["twd_out_total_amount"] / (twd_feat["twd_in_total_amount"] + 1)
twd_feat["twd_active_span_sec"] = (
    twd_feat["twd_last_time"] - twd_feat["twd_first_time"]
).dt.total_seconds()

twd_feat.head()

"""新增了：

	•	log amount
	•	weekend ratio
	•	active days
	•	txn_per_active_day
	•	入金/出金更細統計
	•	gap features

## twd_feat 說明

這一步把多筆法幣出入金紀錄壓縮成每位 user 的摘要。像是：

交易次數

總金額

平均金額

出金比例

unique IP 數

活躍時間跨度

這些特徵都很貼近命題文件提到的法幣進出比率與 IP 異常跳動。
"""

# =========================
# crypto_feat v2
# =========================

crypto_feat = crypto_transfer.groupby("user_id").agg(
    crypto_txn_count=("id", "count"),

    crypto_total_amount=("crypto_amount", "sum"),
    crypto_avg_amount=("crypto_amount", "mean"),
    crypto_max_amount=("crypto_amount", "max"),
    crypto_std_amount=("crypto_amount", "std"),

    crypto_total_twd_value=("twd_value", "sum"),
    crypto_avg_twd_value=("twd_value", "mean"),
    crypto_max_twd_value=("twd_value", "max"),
    crypto_std_twd_value=("twd_value", "std"),

    crypto_avg_amount_log=("crypto_amount_log", "mean"),
    crypto_max_amount_log=("crypto_amount_log", "max"),
    crypto_avg_twd_value_log=("twd_value_log", "mean"),
    crypto_max_twd_value_log=("twd_value_log", "max"),

    crypto_deposit_count=("is_deposit", "sum"),
    crypto_withdraw_count=("is_withdraw", "sum"),

    crypto_external_count=("is_external", "sum"),
    crypto_internal_count=("is_internal", "sum"),

    crypto_relation_count=("has_relation_user", "sum"),
    crypto_has_ip_count=("has_source_ip", "sum"),

    crypto_unique_currency=("currency", "nunique"),
    crypto_unique_protocol=("protocol", "nunique"),
    crypto_unique_from_wallet=("from_wallet_hash", "nunique"),
    crypto_unique_to_wallet=("to_wallet_hash", "nunique"),
    crypto_unique_relation_user=("relation_user_id", "nunique"),
    crypto_unique_ip=("source_ip_hash", "nunique"),

    crypto_night_ratio=("is_night", "mean"),
    crypto_weekend_ratio=("is_weekend", "mean"),

    crypto_first_time=("created_at", "min"),
    crypto_last_time=("created_at", "max")
).reset_index()

# in / out 分開做
crypto_in = crypto_transfer[crypto_transfer["is_deposit"] == 1].groupby("user_id").agg(
    crypto_in_total_amount=("crypto_amount", "sum"),
    crypto_in_avg_amount=("crypto_amount", "mean"),
    crypto_in_max_amount=("crypto_amount", "max"),
    crypto_in_std_amount=("crypto_amount", "std"),
    crypto_in_total_twd_value=("twd_value", "sum"),
    crypto_in_avg_twd_value=("twd_value", "mean")
).reset_index()

crypto_out = crypto_transfer[crypto_transfer["is_withdraw"] == 1].groupby("user_id").agg(
    crypto_out_total_amount=("crypto_amount", "sum"),
    crypto_out_avg_amount=("crypto_amount", "mean"),
    crypto_out_max_amount=("crypto_amount", "max"),
    crypto_out_std_amount=("crypto_amount", "std"),
    crypto_out_total_twd_value=("twd_value", "sum"),
    crypto_out_avg_twd_value=("twd_value", "mean")
).reset_index()

# active days
crypto_active_days = calc_active_day_features(
    crypto_transfer, "user_id", "date_only", "crypto"
)

# gap features
crypto_gap_feat = calc_time_gap_features(
    crypto_transfer, "user_id", "created_at", "crypto"
)

# merge
crypto_feat = crypto_feat.merge(crypto_in, on="user_id", how="left")
crypto_feat = crypto_feat.merge(crypto_out, on="user_id", how="left")
crypto_feat = crypto_feat.merge(crypto_active_days, on="user_id", how="left")
crypto_feat = crypto_feat.merge(crypto_gap_feat, on="user_id", how="left")

# ratios
crypto_feat["crypto_withdraw_ratio"] = crypto_feat["crypto_withdraw_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_deposit_ratio"] = crypto_feat["crypto_deposit_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_external_ratio"] = crypto_feat["crypto_external_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_internal_ratio"] = crypto_feat["crypto_internal_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_relation_ratio"] = crypto_feat["crypto_relation_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_has_ip_ratio"] = crypto_feat["crypto_has_ip_count"] / (crypto_feat["crypto_txn_count"] + 1e-9)
crypto_feat["crypto_withdraw_deposit_ratio"] = crypto_feat["crypto_withdraw_count"] / (crypto_feat["crypto_deposit_count"] + 1)

# density / intensity
crypto_feat["crypto_txn_per_active_day"] = crypto_feat["crypto_txn_count"] / (crypto_feat["crypto_active_days"] + 1)
crypto_feat["crypto_txn_per_relation_user"] = crypto_feat["crypto_txn_count"] / (crypto_feat["crypto_unique_relation_user"] + 1)
crypto_feat["crypto_txn_per_to_wallet"] = crypto_feat["crypto_txn_count"] / (crypto_feat["crypto_unique_to_wallet"] + 1)
crypto_feat["crypto_txn_per_from_wallet"] = crypto_feat["crypto_txn_count"] / (crypto_feat["crypto_unique_from_wallet"] + 1)
crypto_feat["crypto_txn_per_ip"] = crypto_feat["crypto_txn_count"] / (crypto_feat["crypto_unique_ip"] + 1)

crypto_feat["crypto_out_in_amount_ratio"] = crypto_feat["crypto_out_total_twd_value"] / (crypto_feat["crypto_in_total_twd_value"] + 1)

crypto_feat["crypto_active_span_sec"] = (
    crypto_feat["crypto_last_time"] - crypto_feat["crypto_first_time"]
).dt.total_seconds()

crypto_feat.head()

"""新增：

	•	log 特徵
	•	weekend ratio
	•	active days
	•	gap features
	•	in/out 金額分開
	•	density 特徵
	•	wallet / relation 密度

### crypto_feat 說明

這張特徵表最有價值，因為它結合了：

交易金額

內外部交易比例

對手 user 關聯

wallet 多樣性

幣種與協定多樣性

夜間交易比例

這些特徵非常適合用來刻畫人頭戶、資金分流、與可疑轉移模式。
"""

# =========================
# trade_feat v2
# =========================

trade_feat = usdt_twd_trading.groupby("user_id").agg(
    trade_count=("id", "count"),

    trade_total_amount=("amount", "sum"),
    trade_avg_amount=("amount", "mean"),
    trade_max_amount=("amount", "max"),
    trade_std_amount=("amount", "std"),

    trade_avg_amount_log=("amount_log", "mean"),
    trade_max_amount_log=("amount_log", "max"),

    trade_avg_price=("price", "mean"),
    trade_max_price=("price", "max"),
    trade_std_price=("price", "std"),
    trade_avg_price_log=("price_log", "mean"),

    trade_buy_count=("is_buy", "sum"),
    trade_sell_count=("is_sell", "sum"),

    trade_market_count=("is_market", "sum"),
    trade_unique_ip=("source_ip_hash", "nunique"),
    trade_night_ratio=("is_night", "mean"),
    trade_weekend_ratio=("is_weekend", "mean"),

    trade_source_nunique=("source", "nunique"),

    trade_first_time=("updated_at", "min"),
    trade_last_time=("updated_at", "max")
).reset_index()

trade_active_days = calc_active_day_features(
    usdt_twd_trading, "user_id", "date_only", "trade"
)

trade_gap_feat = calc_time_gap_features(
    usdt_twd_trading, "user_id", "updated_at", "trade"
)

trade_feat = trade_feat.merge(trade_active_days, on="user_id", how="left")
trade_feat = trade_feat.merge(trade_gap_feat, on="user_id", how="left")

trade_feat["trade_buy_ratio"] = trade_feat["trade_buy_count"] / (trade_feat["trade_count"] + 1e-9)
trade_feat["trade_sell_ratio"] = trade_feat["trade_sell_count"] / (trade_feat["trade_count"] + 1e-9)
trade_feat["trade_market_ratio"] = trade_feat["trade_market_count"] / (trade_feat["trade_count"] + 1e-9)

trade_feat["trade_txn_per_active_day"] = trade_feat["trade_count"] / (trade_feat["trade_active_days"] + 1)
trade_feat["trade_txn_per_ip"] = trade_feat["trade_count"] / (trade_feat["trade_unique_ip"] + 1)
trade_feat["trade_txn_per_source"] = trade_feat["trade_count"] / (trade_feat["trade_source_nunique"] + 1)

trade_feat["trade_active_span_sec"] = (
    trade_feat["trade_last_time"] - trade_feat["trade_first_time"]
).dt.total_seconds()

trade_feat.head()

"""新增：

	•	log price / log amount
	•	weekend ratio
	•	active days
	•	gap features
	•	source density

### trade_feat 說明

這張表反映掛單簿交易風格。像是：

偏買還是偏賣

市價單比例高不高

是否同時使用多種終端（WEB / APP / API）

夜間掛單比例

這些都可能反映出一般零售交易者與異常帳戶之間的差異。
"""

# =========================
# swap_feat v2
# =========================

swap_feat = usdt_swap.groupby("user_id").agg(
    swap_count=("id", "count"),

    swap_total_twd=("twd_amount", "sum"),
    swap_avg_twd=("twd_amount", "mean"),
    swap_max_twd=("twd_amount", "max"),
    swap_std_twd=("twd_amount", "std"),

    swap_total_crypto=("crypto_amount", "sum"),
    swap_avg_crypto=("crypto_amount", "mean"),
    swap_max_crypto=("crypto_amount", "max"),
    swap_std_crypto=("crypto_amount", "std"),

    swap_avg_twd_log=("twd_amount_log", "mean"),
    swap_max_twd_log=("twd_amount_log", "max"),
    swap_avg_crypto_log=("crypto_amount_log", "mean"),

    swap_buy_count=("is_buy_coin", "sum"),
    swap_sell_count=("is_sell_coin", "sum"),

    swap_night_ratio=("is_night", "mean"),
    swap_weekend_ratio=("is_weekend", "mean"),

    swap_first_time=("created_at", "min"),
    swap_last_time=("created_at", "max")
).reset_index()

swap_buy = usdt_swap[usdt_swap["is_buy_coin"] == 1].groupby("user_id").agg(
    swap_buy_total_twd=("twd_amount", "sum"),
    swap_buy_avg_twd=("twd_amount", "mean")
).reset_index()

swap_sell = usdt_swap[usdt_swap["is_sell_coin"] == 1].groupby("user_id").agg(
    swap_sell_total_twd=("twd_amount", "sum"),
    swap_sell_avg_twd=("twd_amount", "mean")
).reset_index()

swap_active_days = calc_active_day_features(
    usdt_swap, "user_id", "date_only", "swap"
)

swap_gap_feat = calc_time_gap_features(
    usdt_swap, "user_id", "created_at", "swap"
)

swap_feat = swap_feat.merge(swap_buy, on="user_id", how="left")
swap_feat = swap_feat.merge(swap_sell, on="user_id", how="left")
swap_feat = swap_feat.merge(swap_active_days, on="user_id", how="left")
swap_feat = swap_feat.merge(swap_gap_feat, on="user_id", how="left")

swap_feat["swap_buy_ratio"] = swap_feat["swap_buy_count"] / (swap_feat["swap_count"] + 1e-9)
swap_feat["swap_sell_ratio"] = swap_feat["swap_sell_count"] / (swap_feat["swap_count"] + 1e-9)
swap_feat["swap_txn_per_active_day"] = swap_feat["swap_count"] / (swap_feat["swap_active_days"] + 1)
swap_feat["swap_sell_buy_twd_ratio"] = swap_feat["swap_sell_total_twd"] / (swap_feat["swap_buy_total_twd"] + 1)

swap_feat["swap_active_span_sec"] = (
    swap_feat["swap_last_time"] - swap_feat["swap_first_time"]
).dt.total_seconds()

swap_feat.head()

"""新增：

	•	log amount
	•	weekend ratio
	•	active days
	•	gap features
	•	buy/sell 金額分開

### swap_feat 說明

這張特徵表反映使用者的一鍵買賣行為，適合捕捉零售型或快速換匯型操作模式。它和掛單簿交易可以互補，讓模型看到更多面向的行為特徵。

# =========================
# 進階特徵工程：詐騙偵測專用
# =========================

"""
## 1. 網絡關係特徵 (Network Features)



def build_network_features(crypto_transfer):
    """建立轉帳網絡特徵"""
    
    # 基礎網絡統計
    network_out = crypto_transfer[crypto_transfer["has_relation_user"] == 1].groupby("user_id").agg(
        network_out_degree=("relation_user_id", "nunique"),  # 轉給多少不同的人
        network_out_txn_count=("id", "count"),
        network_out_total_value=("twd_value", "sum"),
        network_out_avg_value=("twd_value", "mean")
    ).reset_index()
    
    # 入度：計算有多少人轉給這個 user
    network_in = crypto_transfer[crypto_transfer["has_relation_user"] == 1].groupby("relation_user_id").agg(
        network_in_degree=("user_id", "nunique"),  # 從多少不同的人收到
        network_in_txn_count=("id", "count"),
        network_in_total_value=("twd_value", "sum"),
        network_in_avg_value=("twd_value", "mean")
    ).reset_index()
    network_in = network_in.rename(columns={"relation_user_id": "user_id"})
    
    # 合併出度與入度
    network_feat = network_out.merge(network_in, on="user_id", how="outer").fillna(0)
    
    # 計算網絡特徵比例
    network_feat["network_out_in_degree_ratio"] = network_feat["network_out_degree"] / (network_feat["network_in_degree"] + 1)
    network_feat["network_out_in_value_ratio"] = network_feat["network_out_total_value"] / (network_feat["network_in_total_value"] + 1)
    network_feat["network_total_degree"] = network_feat["network_out_degree"] + network_feat["network_in_degree"]
    network_feat["network_degree_imbalance"] = abs(network_feat["network_out_degree"] - network_feat["network_in_degree"]) / (network_feat["network_total_degree"] + 1)
    
    # 計算二階網絡（朋友的朋友）- 簡化版
    # 找出每個 user 的直接連接對象
    edges = crypto_transfer[crypto_transfer["has_relation_user"] == 1][["user_id", "relation_user_id"]].drop_duplicates()
    
    # 計算共同連接數（三角形結構）
    edge_counts = edges.groupby("user_id").size().reset_index(name="network_direct_connections")
    network_feat = network_feat.merge(edge_counts, on="user_id", how="left").fillna(0)
    
    return network_feat

print("Building network features...")
network_feat = build_network_features(crypto_transfer)
print("network_feat shape:", network_feat.shape)
network_feat.head()

"""
## 2. 錢包地址風險分析 (Wallet Risk Analysis)

識別高風險錢包（被多個用戶使用）並標記使用這些錢包的用戶
"""

def analyze_wallet_risk(crypto_transfer):
    """分析錢包地址的風險程度"""
    
    # 計算每個 to_wallet 的統計
    to_wallet_stats = crypto_transfer[crypto_transfer["has_to_wallet"] == 1].groupby("to_wallet_hash").agg(
        wallet_user_count=("user_id", "nunique"),
        wallet_txn_count=("id", "count"),
        wallet_total_value=("twd_value", "sum"),
        wallet_avg_value=("twd_value", "mean")
    )
    
    # 定義高風險錢包：被超過 5 個不同 user 使用
    high_risk_to_wallets = to_wallet_stats[to_wallet_stats["wallet_user_count"] >= 5].index
    
    # 計算每個 from_wallet 的統計
    from_wallet_stats = crypto_transfer[crypto_transfer["has_from_wallet"] == 1].groupby("from_wallet_hash").agg(
        from_wallet_user_count=("user_id", "nunique"),
        from_wallet_txn_count=("id", "count")
    )
    
    high_risk_from_wallets = from_wallet_stats[from_wallet_stats["from_wallet_user_count"] >= 5].index
    
    # 標記使用高風險錢包的交易
    crypto_transfer_copy = crypto_transfer.copy()
    crypto_transfer_copy["is_high_risk_to_wallet"] = crypto_transfer_copy["to_wallet_hash"].isin(high_risk_to_wallets).astype(int)
    crypto_transfer_copy["is_high_risk_from_wallet"] = crypto_transfer_copy["from_wallet_hash"].isin(high_risk_from_wallets).astype(int)
    
    # 聚合到 user level
    wallet_risk_feat = crypto_transfer_copy.groupby("user_id").agg(
        high_risk_to_wallet_count=("is_high_risk_to_wallet", "sum"),
        high_risk_from_wallet_count=("is_high_risk_from_wallet", "sum"),
        high_risk_to_wallet_ratio=("is_high_risk_to_wallet", "mean"),
        high_risk_from_wallet_ratio=("is_high_risk_from_wallet", "mean")
    ).reset_index()
    
    # 計算錢包重複使用率
    wallet_reuse = crypto_transfer.groupby("user_id").agg(
        to_wallet_reuse_rate=("to_wallet_hash", lambda x: 1 - x.nunique() / (len(x) + 1e-9)),
        from_wallet_reuse_rate=("from_wallet_hash", lambda x: 1 - x.nunique() / (len(x) + 1e-9))
    ).reset_index()
    
    wallet_risk_feat = wallet_risk_feat.merge(wallet_reuse, on="user_id", how="left")
    
    return wallet_risk_feat

print("Analyzing wallet risk...")
wallet_risk_feat = analyze_wallet_risk(crypto_transfer)
print("wallet_risk_feat shape:", wallet_risk_feat.shape)
wallet_risk_feat.head()

"""
## 3. IP 地址異常分析 (IP Anomaly Detection)

檢測 IP 共用、IP 跳動等異常行為
"""

def analyze_ip_patterns(twd_transfer, crypto_transfer, usdt_twd_trading):
    """分析 IP 使用模式"""
    
    # 合併所有表的 IP 資訊
    all_ips = pd.concat([
        twd_transfer[["user_id", "source_ip_hash"]].assign(source="twd"),
        crypto_transfer[["user_id", "source_ip_hash"]].assign(source="crypto"),
        usdt_twd_trading[["user_id", "source_ip_hash"]].assign(source="trade")
    ]).dropna(subset=["source_ip_hash"])
    
    # 計算每個 IP 被多少 user 使用
    ip_user_count = all_ips.groupby("source_ip_hash")["user_id"].nunique()
    
    # 定義共用 IP：被超過 3 個 user 使用
    shared_ips = ip_user_count[ip_user_count >= 3].index
    
    # 標記共用 IP
    all_ips["is_shared_ip"] = all_ips["source_ip_hash"].isin(shared_ips).astype(int)
    
    # 聚合到 user level
    ip_feat = all_ips.groupby("user_id").agg(
        total_unique_ips=("source_ip_hash", "nunique"),
        total_ip_usage_count=("source_ip_hash", "count"),
        shared_ip_count=("is_shared_ip", "sum"),
        shared_ip_ratio=("is_shared_ip", "mean"),
        ip_source_diversity=("source", "nunique")  # 在多少種交易類型中使用 IP
    ).reset_index()
    
    # IP 跳動率（IP 數量 / 交易次數）
    ip_feat["ip_jump_rate"] = ip_feat["total_unique_ips"] / (ip_feat["total_ip_usage_count"] + 1e-9)
    
    # 計算每個 user 在不同交易類型中的 IP 重疊度
    user_ip_by_source = all_ips.groupby(["user_id", "source"])["source_ip_hash"].apply(set).reset_index()
    
    # 計算 IP 一致性（跨交易類型使用相同 IP 的程度）
    def calc_ip_consistency(group):
        if len(group) <= 1:
            return 1.0
        sets = group["source_ip_hash"].tolist()
        intersection = set.intersection(*sets)
        union = set.union(*sets)
        return len(intersection) / (len(union) + 1e-9) if len(union) > 0 else 0
    
    ip_consistency = user_ip_by_source.groupby("user_id").apply(calc_ip_consistency).reset_index(name="ip_consistency_score")
    ip_feat = ip_feat.merge(ip_consistency, on="user_id", how="left").fillna(1.0)
    
    return ip_feat

print("Analyzing IP patterns...")
ip_feat = analyze_ip_patterns(twd_transfer, crypto_transfer, usdt_twd_trading)
print("ip_feat shape:", ip_feat.shape)
ip_feat.head()

"""
## 4. 時間序列異常模式 (Temporal Anomaly Detection)

檢測異常的時間模式，如集中在特定時段的交易
"""

def extract_temporal_anomalies(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap):
    """提取時間序列異常特徵"""
    
    temporal_feats = []
    
    # 對每種交易類型計算時間熵
    for df, prefix, time_col in [
        (twd_transfer, "twd", "created_at"),
        (crypto_transfer, "crypto", "created_at"),
        (usdt_twd_trading, "trade", "updated_at"),
        (usdt_swap, "swap", "created_at")
    ]:
        # 計算每小時交易分布的熵
        def calc_hour_entropy(hours):
            if len(hours) == 0:
                return 0
            counts = hours.value_counts(normalize=True)
            entropy = -sum(p * np.log(p + 1e-9) for p in counts)
            return entropy
        
        hour_entropy = df.groupby("user_id")["hour"].apply(calc_hour_entropy).reset_index(name=f"{prefix}_hour_entropy")
        
        # 計算星期分布的熵
        day_entropy = df.groupby("user_id")["day_of_week"].apply(calc_hour_entropy).reset_index(name=f"{prefix}_day_entropy")
        
        # 合併
        temp_feat = hour_entropy.merge(day_entropy, on="user_id", how="outer")
        temporal_feats.append(temp_feat)
    
    # 合併所有時間特徵
    temporal_feat = temporal_feats[0]
    for feat in temporal_feats[1:]:
        temporal_feat = temporal_feat.merge(feat, on="user_id", how="outer")
    
    temporal_feat = temporal_feat.fillna(0)
    
    # 計算整體時間集中度（低熵 = 高度集中在特定時段）
    entropy_cols = [col for col in temporal_feat.columns if "entropy" in col]
    temporal_feat["avg_time_entropy"] = temporal_feat[entropy_cols].mean(axis=1)
    temporal_feat["min_time_entropy"] = temporal_feat[entropy_cols].min(axis=1)
    
    return temporal_feat

print("Extracting temporal anomalies...")
temporal_feat = extract_temporal_anomalies(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap)
print("temporal_feat shape:", temporal_feat.shape)
temporal_feat.head()

"""
## 5. 金額模式異常 (Amount Pattern Anomalies)

檢測整數金額偏好、異常金額分布等
"""

def detect_amount_anomalies(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap):
    """檢測金額模式異常"""
    
    amount_feats = []
    
    # TWD transfer 金額模式
    twd_amount_feat = twd_transfer.groupby("user_id").agg(
        twd_round_1000_ratio=("amount", lambda x: (x % 1000 == 0).mean()),
        twd_round_10000_ratio=("amount", lambda x: (x % 10000 == 0).mean()),
        twd_round_100000_ratio=("amount", lambda x: (x % 100000 == 0).mean()),
        twd_amount_cv=("amount", lambda x: x.std() / (x.mean() + 1e-9)),
        twd_amount_skew=("amount", lambda x: x.skew() if len(x) > 2 else 0),
        twd_amount_kurtosis=("amount", lambda x: x.kurtosis() if len(x) > 3 else 0)
    ).reset_index()
    amount_feats.append(twd_amount_feat)
    
    # Crypto transfer 金額模式
    crypto_amount_feat = crypto_transfer.groupby("user_id").agg(
        crypto_round_ratio=("crypto_amount", lambda x: (x == x.round()).mean()),
        crypto_twd_value_cv=("twd_value", lambda x: x.std() / (x.mean() + 1e-9)),
        crypto_twd_value_skew=("twd_value", lambda x: x.skew() if len(x) > 2 else 0)
    ).reset_index()
    amount_feats.append(crypto_amount_feat)
    
    # Trading 金額模式
    trade_amount_feat = usdt_twd_trading.groupby("user_id").agg(
        trade_amount_cv=("amount", lambda x: x.std() / (x.mean() + 1e-9)),
        trade_price_cv=("price", lambda x: x.std() / (x.mean() + 1e-9))
    ).reset_index()
    amount_feats.append(trade_amount_feat)
    
    # Swap 金額模式
    swap_amount_feat = usdt_swap.groupby("user_id").agg(
        swap_twd_cv=("twd_amount", lambda x: x.std() / (x.mean() + 1e-9)),
        swap_round_10000_ratio=("twd_amount", lambda x: (x % 10000 == 0).mean())
    ).reset_index()
    amount_feats.append(swap_amount_feat)
    
    # 合併所有金額特徵
    amount_feat = amount_feats[0]
    for feat in amount_feats[1:]:
        amount_feat = amount_feat.merge(feat, on="user_id", how="outer")
    
    amount_feat = amount_feat.fillna(0)
    
    return amount_feat

print("Detecting amount anomalies...")
amount_feat = detect_amount_anomalies(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap)
print("amount_feat shape:", amount_feat.shape)
amount_feat.head()

"""
## 6. 跨表資金流向特徵 (Cross-table Fund Flow)

分析資金在不同交易類型間的流動模式
"""

def calculate_fund_flow_patterns(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap):
    """計算跨表資金流向特徵"""
    
    # 計算每個 user 在各表的首次和最後交易時間
    twd_time = twd_transfer.groupby("user_id")["created_at"].agg(["min", "max"]).reset_index()
    twd_time.columns = ["user_id", "twd_first", "twd_last"]
    
    crypto_time = crypto_transfer.groupby("user_id")["created_at"].agg(["min", "max"]).reset_index()
    crypto_time.columns = ["user_id", "crypto_first", "crypto_last"]
    
    trade_time = usdt_twd_trading.groupby("user_id")["updated_at"].agg(["min", "max"]).reset_index()
    trade_time.columns = ["user_id", "trade_first", "trade_last"]
    
    swap_time = usdt_swap.groupby("user_id")["created_at"].agg(["min", "max"]).reset_index()
    swap_time.columns = ["user_id", "swap_first", "swap_last"]
    
    # 合併時間資訊
    flow_feat = twd_time.merge(crypto_time, on="user_id", how="outer")
    flow_feat = flow_feat.merge(trade_time, on="user_id", how="outer")
    flow_feat = flow_feat.merge(swap_time, on="user_id", how="outer")
    
    # 計算整體活動時間範圍
    time_cols = ["twd_first", "crypto_first", "trade_first", "swap_first"]
    flow_feat["overall_first_time"] = flow_feat[time_cols].min(axis=1)
    
    time_cols = ["twd_last", "crypto_last", "trade_last", "swap_last"]
    flow_feat["overall_last_time"] = flow_feat[time_cols].max(axis=1)
    
    flow_feat["overall_active_span_sec"] = (
        flow_feat["overall_last_time"] - flow_feat["overall_first_time"]
    ).dt.total_seconds()
    
    # 計算快速資金流模式（24小時內的跨表操作）
    # 例如：TWD 入金後 24 小時內有 crypto 出金
    flow_feat["twd_to_crypto_gap_sec"] = (
        flow_feat["crypto_first"] - flow_feat["twd_first"]
    ).dt.total_seconds()
    
    flow_feat["crypto_to_twd_gap_sec"] = (
        flow_feat["twd_first"] - flow_feat["crypto_first"]
    ).dt.total_seconds()
    
    # 標記快速流轉（< 24 小時）
    flow_feat["is_fast_twd_to_crypto"] = (
        (flow_feat["twd_to_crypto_gap_sec"] > 0) & 
        (flow_feat["twd_to_crypto_gap_sec"] < 86400)
    ).astype(int)
    
    flow_feat["is_fast_crypto_to_twd"] = (
        (flow_feat["crypto_to_twd_gap_sec"] > 0) & 
        (flow_feat["crypto_to_twd_gap_sec"] < 86400)
    ).astype(int)
    
    # 計算交易類型多樣性
    flow_feat["has_twd"] = flow_feat["twd_first"].notna().astype(int)
    flow_feat["has_crypto"] = flow_feat["crypto_first"].notna().astype(int)
    flow_feat["has_trade"] = flow_feat["trade_first"].notna().astype(int)
    flow_feat["has_swap"] = flow_feat["swap_first"].notna().astype(int)
    flow_feat["txn_type_diversity"] = (
        flow_feat["has_twd"] + flow_feat["has_crypto"] + 
        flow_feat["has_trade"] + flow_feat["has_swap"]
    )
    
    # 只保留數值特徵
    numeric_cols = ["user_id", "overall_active_span_sec", "twd_to_crypto_gap_sec", 
                    "crypto_to_twd_gap_sec", "is_fast_twd_to_crypto", "is_fast_crypto_to_twd",
                    "has_twd", "has_crypto", "has_trade", "has_swap", "txn_type_diversity"]
    
    flow_feat = flow_feat[numeric_cols].fillna(0)
    
    return flow_feat

print("Calculating fund flow patterns...")
flow_feat = calculate_fund_flow_patterns(twd_transfer, crypto_transfer, usdt_twd_trading, usdt_swap)
print("flow_feat shape:", flow_feat.shape)
flow_feat.head()

"""
## 7. 行為序列特徵 (Behavioral Sequence Features)

分析用戶的操作序列模式
"""

def extract_sequence_features(twd_transfer, crypto_transfer):
    """提取行為序列特徵"""
    
    # 合併 TWD 和 Crypto 交易，建立時間序列
    twd_seq = twd_transfer[["user_id", "created_at", "kind"]].copy()
    twd_seq["action"] = twd_seq["kind"].map({0: "twd_in", 1: "twd_out"})
    twd_seq = twd_seq[["user_id", "created_at", "action"]]
    
    crypto_seq = crypto_transfer[["user_id", "created_at", "kind"]].copy()
    crypto_seq["action"] = crypto_seq["kind"].map({0: "crypto_in", 1: "crypto_out"})
    crypto_seq = crypto_seq[["user_id", "created_at", "action"]]
    
    # 合併並排序
    all_seq = pd.concat([twd_seq, crypto_seq]).sort_values(["user_id", "created_at"])
    
    # 計算連續相同操作的次數
    all_seq["prev_action"] = all_seq.groupby("user_id")["action"].shift(1)
    all_seq["is_repeat"] = (all_seq["action"] == all_seq["prev_action"]).astype(int)
    
    # 聚合序列特徵
    seq_feat = all_seq.groupby("user_id").agg(
        total_actions=("action", "count"),
        repeat_action_ratio=("is_repeat", "mean"),
        unique_action_types=("action", "nunique")
    ).reset_index()
    
    # 檢測典型詐騙序列：twd_in -> crypto_out (快速出金)
    all_seq["next_action"] = all_seq.groupby("user_id")["action"].shift(-1)
    all_seq["time_to_next"] = all_seq.groupby("user_id")["created_at"].diff(-1).dt.total_seconds().abs()
    
    # 標記可疑序列
    all_seq["is_suspicious_seq"] = (
        (all_seq["action"] == "twd_in") & 
        (all_seq["next_action"] == "crypto_out") &
        (all_seq["time_to_next"] < 3600)  # 1小時內
    ).astype(int)
    
    suspicious_seq = all_seq.groupby("user_id")["is_suspicious_seq"].agg(["sum", "mean"]).reset_index()
    suspicious_seq.columns = ["user_id", "suspicious_seq_count", "suspicious_seq_ratio"]
    
    seq_feat = seq_feat.merge(suspicious_seq, on="user_id", how="left").fillna(0)
    
    return seq_feat

print("Extracting sequence features...")
seq_feat = extract_sequence_features(twd_transfer, crypto_transfer)
print("seq_feat shape:", seq_feat.shape)
seq_feat.head()

"""
## 進階特徵總結

已建立以下 7 類進階特徵：

1. network_feat: 網絡關係特徵（出入度、網絡密度）
2. wallet_risk_feat: 錢包風險特徵（高風險錢包使用）
3. ip_feat: IP 異常特徵（IP 共用、IP 跳動）
4. temporal_feat: 時間異常特徵（時間熵、集中度）
5. amount_feat: 金額異常特徵（整數偏好、分布異常）
6. flow_feat: 資金流向特徵（跨表快速流轉）
7. seq_feat: 行為序列特徵（可疑操作序列）

接下來將這些特徵合併到主特徵表中。
"""

## 合併所有特徵表

print("twd_feat exists:", "twd_feat" in globals())
print("crypto_feat exists:", "crypto_feat" in globals())
print("trade_feat exists:", "trade_feat" in globals())
print("swap_feat exists:", "swap_feat" in globals())

feature_df = user_info.copy()

# 合併基礎特徵
feature_df = feature_df.merge(twd_feat, on="user_id", how="left")
feature_df = feature_df.merge(crypto_feat, on="user_id", how="left")
feature_df = feature_df.merge(trade_feat, on="user_id", how="left")
feature_df = feature_df.merge(swap_feat, on="user_id", how="left")

print("After basic features:", feature_df.shape)

# 合併進階特徵
print("\nMerging advanced features...")
feature_df = feature_df.merge(network_feat, on="user_id", how="left")
print("After network_feat:", feature_df.shape)

feature_df = feature_df.merge(wallet_risk_feat, on="user_id", how="left")
print("After wallet_risk_feat:", feature_df.shape)

feature_df = feature_df.merge(ip_feat, on="user_id", how="left")
print("After ip_feat:", feature_df.shape)

feature_df = feature_df.merge(temporal_feat, on="user_id", how="left")
print("After temporal_feat:", feature_df.shape)

feature_df = feature_df.merge(amount_feat, on="user_id", how="left")
print("After amount_feat:", feature_df.shape)

feature_df = feature_df.merge(flow_feat, on="user_id", how="left")
print("After flow_feat:", feature_df.shape)

feature_df = feature_df.merge(seq_feat, on="user_id", how="left")
print("After seq_feat:", feature_df.shape)

print("\nFinal feature_df shape:", feature_df.shape)
feature_df.head()

"""### 為什麼 merge 後會有缺值

merge 之後的缺值通常不代表資料錯誤，而是：

某 user 沒有做過某一種交易

因此對應的聚合特徵不存在

這種情況通常可以在非時間欄位補 0。

### 進階特徵說明

新增的進階特徵包括：

1. 網絡特徵：識別資金流向網絡中的異常節點
2. 錢包風險：標記使用高風險共用錢包的用戶
3. IP 異常：檢測 IP 共用和跳動行為
4. 時間異常：識別集中在特定時段的可疑交易
5. 金額異常：檢測整數金額偏好等異常模式
6. 資金流向：追蹤跨表快速資金流轉
7. 行為序列：識別典型詐騙操作序列

這些特徵能更精準地捕捉詐騙行為模式。
"""

datetime_cols = feature_df.select_dtypes(include=["datetime64[ns]"]).columns.tolist()
print("datetime_cols:", datetime_cols)

for col in feature_df.columns:
    if col not in datetime_cols:
        feature_df[col] = feature_df[col].fillna(0)

feature_df.head()

"""# 建立 train_df 與 test_df

最後一步是把 feature_df 分別接回：

train_label → 建立 train_df

predict_label → 建立 test_df

這樣就得到下一份 Colab 建模所需的資料。
"""

train_df = train_label.merge(feature_df, on="user_id", how="left")
test_df = predict_label.merge(feature_df, on="user_id", how="left")

for col in train_df.columns:
    if col not in datetime_cols:
        train_df[col] = train_df[col].fillna(0)

for col in test_df.columns:
    if col not in datetime_cols:
        test_df[col] = test_df[col].fillna(0)

print("train_df:", train_df.shape)
print("test_df:", test_df.shape)

train_df.head()

test_df = predict_label.merge(feature_df, on="user_id", how="left")

for col in test_df.columns:
    if col not in datetime_cols:
        test_df[col] = test_df[col].fillna(0)

print(test_df.shape)
test_df.head()

"""輸出成果檢查

如果一切正常，通常會看到：

train_df 大約 51,017 列

test_df 大約 12,753 列

train_df 比 test_df 多一欄 status

這代表我們已經成功把原始多表交易資料轉成 user-level 建模資料。

### 存出中間成果給 Colab-2 使用

Colab-1 的任務到這裡就完成了。我們會把整理好的資料存出來，讓 Colab-2 直接拿來做模型訓練、調參、threshold tuning 與 submission。
"""

feature_df.to_csv("feature_df.csv", index=False)
train_df.to_csv("train_df.csv", index=False)
test_df.to_csv("test_df.csv", index=False)

"""# Colab-1 總結

到這一步，我們已經完成：

API 抓資料

Pagination fetch

DataFrame 建立

CSV snapshot

初步 EDA

Data cleaning

Feature engineering

建立 user-level train_df / test_df

接下來的 Colab-2 就會專注在模型訓練與評估，而不需要重新做資料工程。
"""